# Generated by Django 5.1.6 on 2025-04-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinvetory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarInvetory',
            new_name='CarInventory',
        ),
    ]
